### ISSUE TITLE
prefetch.so :undefined symbol: cuEventCreate

### ISSUE THREAD

**Issue by kimdesok** [aetherAI/tensorflow-huge-model-support#2]
Hi, 
Can anyone help me?
I am stuck with the problem as below:

I did 'pip install .' as explained.  It did not result in any errors but I was NOT sure if it installed the prefetch module correctly.

When I ran 'python -m whole_slide_cnn.train --config  train_configs/config_wholeslide_2x.yaml' , it went smoothly upto the line where the cuEventCreate is called from the prefetch.so.  It resulted an error that says 'undefined symbol: cuEventCreate'

See the error message below.

### Initializing dataloaders ###
Train dataloader contains 418 slides on rank 0. The first one is /home/ubuntu/Datasets/Slides/TCGA-49-4490-01Z-00-DX6.0a04ad8e-7f33-4496-bd9e-0110ec33f887.svs.
Val dataloader contains 98 slides on rank 0. The first one is /home/ubuntu/Datasets/Slides/TCGA-50-5939-01Z-00-DX1.745D7503-0744-46B1-BC89-EBB8FCE2D55C.svs.
### Start training ###
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow1.15_py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/tensorflow1.15_py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/exercises/whole_slide_cnn/whole_slide_cnn/train.py", line 300, in <module>
    verbose=(1 if is_rank0 else 0),
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 603, in fit
    steps_name='steps_per_epoch')
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 178, in model_iteration
    mode=mode)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 105, in configure_callbacks
    callback_list.set_model(callback_model)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 219, in set_model
    callback.set_model(model)
  File "/home/ubuntu/anaconda3/envs/tensorflow1.15_py37/lib/python3.7/site-packages/tensorflow_huge_model_support/tf_keras.py", line 50, in set_model
    self._hms = hms = HMS(fwd_op, bwd_op, hvd=self._hvd, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow1.15_py37/lib/python3.7/site-packages/tensorflow_huge_model_support/hms.py", line 775, in __init__
    self._pf_module = tf.load_op_library(hms_pf_module_path)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/exercises/tensorflow-huge-model-support/prefetch_module/prefetch.so: undefined symbol: cuEventCreate

**Comment by kimdesok** [comment]
This problem was solved by installing cudatoolkit=10.0
